name: Check package

on: [push, pull_request]

jobs:
  check_document:
    name: Check packaging 📦
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 20
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install tools
      run: |
        pip install -U pip
        pip install tox tox-gh-actions coveralls
    - name: Check
      run: tox
      env:
        PYTEST_ADDOPTS: --cov-config=pyproject.toml --cov --cov-append --verbose
    - name: Upload Coverage
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
