name: Check and unittest

on: push

jobs:
  check_document:
    name: Check code, docs and packaging 📦
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 20
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install test dependencies
      run: |
        pip install -U pip
        pip install tox tox-gh-actions
    - name: Run check
      run: tox
