name: "Check combinations.json"
on:
  # Run at midnight on the first of every month
  schedule:
  - cron: "0 0 1 * *"

  push:

jobs:
  check_combinations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 20
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build and install
      run: |
        python setup.py --version
        python -m pip install ./ --user
    - name: Install generate_combinations dependencies
      run: pip install PyGithub GitPython tqdm
    - name: Check combinations.json
      run: PYTHONPATH=$(pwd) python3 ci/generate_combinations.py make_PR

